spring:
  application:
    name: beer-system
  profiles:
    active:
      - localmysql
  flyway:
    enabled: false
#  jpa:
#    properties:
#      jakarta:
#        persistence:
#          schema-generation:
#            scripts:
#              action: drop-and-create
#              create-source: metadata
#              drop-target: drop-and-create.sql
#              create-target: drop-and-create.sql

logging:
  level:
    root: info
    web: info
    sql: debug
    com.juhmaran.beersystem: info